open_app:
  description: Open an app on the TV.
  fields:
    entity_id:
      description: Name(s) of the TV(s) to open an app on
      example: media_player.living_room_tv
    app:
      description: Name of the app to open
      example: Netflix
send_command:
  description: Send a command to the TV.
  fields:
    entity_id:
      description: Name(s) of the TV(s) to send a command to
      example: media_player.living_room_tv
    command:
      description: Name of the command to send
      example: ChannelUp
